apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  # No additional metadata required for Kubernetes secret store
  # Secrets are accessed via secretKeyRef in other components

scopes:
- backend-api
- recurring-task-service
- notification-service
- audit-service
- sync-service
