# Dapr Pub/Sub Component: Redpanda (Kafka-compatible)
# For Minikube local development
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    # Redpanda broker endpoint (local or Redpanda Cloud)
    - name: brokers
      value: "localhost:19092"

    # Authentication
    - name: authType
      value: "password"

    # Redpanda uses SCRAM-SHA-256 SASL mechanism
    - name: saslMechanism
      value: "SCRAM-SHA-256"

    # Redpanda credentials from Kubernetes secret
    - name: saslUsername
      secretKeyRef:
        name: redpanda-creds
        key: sasl-username

    - name: saslPassword
      secretKeyRef:
        name: redpanda-creds
        key: sasl-password

    # Consumer group (uses Dapr app-id)
    - name: consumerGroup
      value: "{APP_ID}"

    # Start from oldest message on first connect
    - name: initialOffset
      value: "oldest"

    # Maximum message size (1MB)
    - name: maxMessageBytes
      value: "1048576"

    # Retry interval on consume errors
    - name: consumeRetryInterval
      value: "1000ms"

    # Kafka protocol version
    - name: version
      value: "3.0.0"

    # TLS configuration (set to false for local Redpanda, true for Redpanda Cloud)
    - name: disableTls
      value: "true"
