# Dapr Secret Store Component: Kubernetes Secrets
# Spec 8 - Event-Driven Architecture
# Used for: Oracle Streaming Service credentials, SendGrid API key, FCM server key
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
